# Tugas Minggu ke-7 Pembelajaran Mesin
| Name           | NRP        | Kelas     |
| ---            | ---        | ----------|
| Algof Kristian Zega | 5025231235 | Pembelajaran Mesin (D) |

**Source Kaggle** <br>
[https://www.kaggle.com/competitions/hands-on-2-pembelajaran-mesin-2025](https://www.kaggle.com/competitions/hands-on-2-pembelajaran-mesin-2025/overview)

## 1. Problem Definition

### 1.1 Overview

This dataset simulates user behavior on an e-commerce website using Google Analytics session-level data. Each row represents a unique session, with various behavioral, traffic source, and device-related attributes. The goal is to predict whether a user will make a purchase on a return visit, based on information from their current session.

### 1.2 Objective

Your task is to build a model that predicts the binary outcome:

Will the user make a purchase if they return in a later session?

This can help businesses understand visitor intent, personalize user experience, and retarget high-quality traffic.

## 2. Data Collection

Download dataset dari Kaggle

```sh
kaggle competitions download -c hands-on-2-pembelajaran-mesin-2025
```

In [32]:
import pandas as pd

train_df = pd.read_csv('../train.csv')
test_df = pd.read_csv('../test.csv')
submission_df = pd.read_csv('../sample_submission.csv')

## 3. Exploratory Data Analysis

### 3.1 Features

| **Features**               | **Definition**                                                                 |
|----------------------------|--------------------------------------------------------------------------------|
| unique_session_id          | Unique identifier for each session (based on fullVisitorId and visitId).      |
| bounces                    | Indicates if the session ended with only one pageview.                        |
| time_on_site              | Total time spent on the site during the session (in seconds).                 |
| pageviews                  | Number of pages viewed during the session.                                    |
| hits                       | Total number of user interactions during the session.                         |
| session_quality_dim        | Proprietary quality score (1–100) estimating purchase intent.                 |
| latest_ecommerce_progress  | The furthest stage reached in the e-commerce funnel.                          |
| avg_time_per_page          | Average time per page (calculated as time_on_site / pageviews).               |
| source                     | The source of the traffic (e.g., google, bing, direct).                       |
| medium                     | The medium of the traffic (e.g., organic, cpc, referral).                     |
| channelGrouping            | High-level channel category (e.g., Referral, Organic Search, Direct).         |
| deviceCategory             | The category of the device used (desktop, tablet, mobile).                    |
| operatingSystem            | The category of the device operating system used.                             |
| browser                    | The category of the device browser used.                                      |
| country                    | Country from where the user accessed the site.                                |
| city                       | City from where the user accessed the site.                                   |

In [33]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         4000 non-null   int64
 1   unique_session_id          4000 non-null   object
 2   bounces                    4000 non-null   int64
 3   time_on_site               4000 non-null   int64
 4   pageviews                  4000 non-null   int64
 5   hits                       4000 non-null   int64
 6   session_quality_dim        4000 non-null   int64
 7   latest_ecommerce_progress  4000 non-null   int64
 8   avg_time_per_page          2724 non-null   float64
 9   source                     4000 non-null   object
 10  medium                     3404 non-null   object
 11  channelGrouping            4000 non-null   object
 12  deviceCategory             4000 non-null   object
 13  operatingSystem            3984 non-null   object
 14  browser                    4000 non-null   object
 15  country                    4000 non-null   object
 16  city                       3176 non-null   object
 17  will_buy_on_return_visit   4000 non-null   int64
dtypes: float64(1), int64(8), object(9)
memory usage: 562.6+ KB

In [34]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1000 non-null   int64
 1   unique_session_id          1000 non-null   object
 2   bounces                    1000 non-null   int64
 3   time_on_site               1000 non-null   int64
 4   pageviews                  1000 non-null   int64
 5   hits                       1000 non-null   int64
 6   session_quality_dim        1000 non-null   int64
 7   latest_ecommerce_progress  1000 non-null   int64
 8   avg_time_per_page          651 non-null    float64
 9   source                     1000 non-null   object
 10  medium                     841 non-null    object
 11  channelGrouping            1000 non-null   object
 12  deviceCategory             1000 non-null   object
 13  operatingSystem            996 non-null    object
 14  browser                    1000 non-null   object
 15  country                    1000 non-null   object
 16  city                       818 non-null    object
dtypes: float64(1), int64(7), object(9)
memory usage: 132.9+ KB

In [35]:
train_df.describe()

,id,bounces,time_on_site,pageviews,hits,session_quality_dim,latest_ecommerce_progress,avg_time_per_page,will_buy_on_return_visit
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000,4000.000000,2724.000000,4000.000000
mean,2486.020750,0.318000,243.913250,7.183750,8.796250,0.95875,1.390750,34.464465,0.502250
std,1439.917566,0.465758,483.536977,10.606866,14.122184,8.39197,2.195511,63.281845,0.500057
min,0.000000,0.000000,0.000000,1.000000,1.000000,0.00000,0.000000,0.500000,0.000000
25%,1258.750000,0.000000,0.000000,1.000000,1.000000,0.00000,0.000000,10.139971,0.000000
50%,2481.500000,0.000000,41.000000,3.000000,3.000000,0.00000,0.000000,20.000000,1.000000
75%,3706.250000,1.000000,247.000000,9.000000,11.000000,0.00000,2.000000,32.967391,1.000000
max,4998.000000,1.000000,5820.000000,194.000000,262.000000,99.00000,6.000000,969.000000,1.000000

In [36]:
test_df.describe()

,id,bounces,time_on_site,pageviews,hits,session_quality_dim,latest_ecommerce_progress,avg_time_per_page
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,651.000000
mean,2553.417000,0.349000,226.805000,6.51500,7.989000,1.125000,1.318000,38.664124
std,1457.319184,0.476892,446.825167,9.28461,12.940183,9.451492,2.146971,88.677771
min,44.000000,0.000000,0.000000,1.00000,1.000000,0.000000,0.000000,0.500000
25%,1224.000000,0.000000,0.000000,1.00000,1.000000,0.000000,0.000000,10.775000
50%,2579.000000,0.000000,36.000000,3.00000,3.000000,0.000000,0.000000,20.000000
75%,3869.750000,1.000000,219.000000,9.00000,10.000000,0.000000,2.000000,33.968750
max,4999.000000,1.000000,2928.000000,100.00000,157.000000,99.000000,6.000000,1464.000000

### 3.2 Analisis Kolom Objek

In [37]:
# Mencari jumlah tipe/kemungkinan isi dari masing-masing kolom objek, baik di train dataframe maupun di test dataframe
# Tujuannya untuk menentukan tipe encoding yang tepat untuk setiap kolom objek
object_col = ['source', 'channelGrouping', 'deviceCategory', 'operatingSystem', 'browser', 'country']

print("Train Dataframe")
for col_name in object_col:
	print(f"Unique values in '{col_name}':", len(train_df[col_name].unique()))
print("\nTest Dataframe")
for col_name in object_col:
	print(f"Unique values in '{col_name}':", len(test_df[col_name].unique()))

# Jika jumlah unique values lebih besar dari 15, maka metode encoding yang cocok adalah 'Target Encoder'
# Jika dibawah 15 maka One Hot Encoding masih cocok
# Karena One Hot Encoding akan membentuk satu kolom True/False untuk setiap kemungkinan nilai di kolom tersebut
# Sehingga jika terdapat banyak unique values, jumlah kolom yang dihasilkan akan sangat banyak dan mempengaruhi kinerja model
# Seperti
# 1. Dimensi menjadi sangat besar
# 2. Sparse matrix
# 3. Komputasi jadi lebih mahal

del object_col, col_name

Train Dataframe
Unique values in 'source': 79
Unique values in 'channelGrouping': 7
Unique values in 'deviceCategory': 3
Unique values in 'operatingSystem': 9
Unique values in 'browser': 14
Unique values in 'country': 102

Test Dataframe
Unique values in 'source': 29
Unique values in 'channelGrouping': 7
Unique values in 'deviceCategory': 3
Unique values in 'operatingSystem': 8
Unique values in 'browser': 12
Unique values in 'country': 70

In [38]:
print("Train Dataframe")
train_df.isna().sum()

Train Dataframe

id                              0
unique_session_id               0
bounces                         0
time_on_site                    0
pageviews                       0
hits                            0
session_quality_dim             0
latest_ecommerce_progress       0
avg_time_per_page            1276
source                          0
medium                        596
channelGrouping                 0
deviceCategory                  0
operatingSystem                16
browser                         0
country                         0
city                          824
will_buy_on_return_visit        0
dtype: int64

In [39]:
print("Test Dataframe")
test_df.isna().sum()

Test Dataframe

id                             0
unique_session_id              0
bounces                        0
time_on_site                   0
pageviews                      0
hits                           0
session_quality_dim            0
latest_ecommerce_progress      0
avg_time_per_page            349
source                         0
medium                       159
channelGrouping                0
deviceCategory                 0
operatingSystem                4
browser                        0
country                        0
city                         182
dtype: int64

## 4. Data Preprocessing

### 4.1 Train Dataset

Median imputation untuk feature `avg_time_per_page`

In [40]:
median = train_df['avg_time_per_page'].median()
train_df['avg_time_per_page'] = train_df['avg_time_per_page'].fillna(median)

del median

Most frequent imputation untuk feature `operatingSystem`

In [41]:
most_frequent = train_df['operatingSystem'].mode()[0]
train_df['operatingSystem'] = train_df['operatingSystem'].fillna(most_frequent)

del most_frequent

Drop kolom feature `city` dan `medium` karena terlalu banyak missing value

In [42]:
train_df.drop(['city', 'medium'], axis=1, inplace=True)

Drop kolom `id` dan `unique_session_id` karena tidak terlalu berpengaruh, hanya sebagai penanda baris saja

In [43]:
train_df.drop(['id', 'unique_session_id'], axis=1, inplace=True)

---

### 4.2 Test Dataset

Median imputation untuk feature `avg_time_per_page`

In [44]:
median = test_df['avg_time_per_page'].median()
test_df['avg_time_per_page'] = test_df['avg_time_per_page'].fillna(median)

Most frequent imputation untuk feature `operatingSystem`

In [45]:
most_frequent = test_df['operatingSystem'].mode()[0]
test_df['operatingSystem'] = test_df['operatingSystem'].fillna(most_frequent)

Drop kolom feature `city` dan `medium` karena terlalu banyak missing value

In [46]:
test_df.drop(['city', 'medium'], axis=1, inplace=True)

Drop kolom `id` dan `unique_session_id` karena tidak terlalu berpengaruh

In [47]:
test_df.drop(['id', 'unique_session_id'], axis=1, inplace=True)

### 4.3 Feature Selection

Chi-Square

In [48]:
from scipy.stats import chi2_contingency

# Fungsi untuk melakukan Chi-Square Test
def chi_square_test(feature, target):
    contingency_table = pd.crosstab(train_df[feature], train_df[target])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    return p

# Menghitung nilai p untuk setiap fitur
# Semakin kecil P-value nya berarti ada hubungan yang signifikan secara statistik antara fitur dan target.
# Sebaliknya, p-value besar menunjukkan bahwa tidak ada bukti cukup untuk menyatakan bahwa fitur dan target saling berhubungan.
features = ['source', 'channelGrouping', 'deviceCategory', 'operatingSystem', 'browser', 'country']
p_values = {feature: chi_square_test(feature, 'will_buy_on_return_visit') for feature in features}

# Membuat DataFrame untuk menampilkan hasil
p_values_df = pd.DataFrame(list(p_values.items()), columns=['Feature', 'P-value'])
p_values_df = p_values_df.sort_values(by='P-value')

print(p_values_df)

del features, p_values, p_values_df

           Feature        P-value
0           source   0.000000e+00
5          country   0.000000e+00
1  channelGrouping  9.150436e-272
4          browser  3.458583e-228
3  operatingSystem  7.373340e-186
2   deviceCategory  9.984255e-128

ANOVA

In [49]:
from sklearn.feature_selection import f_classif, SelectKBest

# List nama-nama kolom yang bertipe numerik (float64 atau int64)
num_cols = ['bounces', 'time_on_site', 'pageviews', 'hits', 'session_quality_dim', 'latest_ecommerce_progress', 'avg_time_per_page']

X_anova = train_df[num_cols]
y_anova = train_df['will_buy_on_return_visit']

# Menggunakan ANOVA F-test untuk feature selection
selector = SelectKBest(score_func=f_classif, k='all')
selector.fit(X_anova, y_anova)

# Mendapatkan skor ANOVA F untuk setiap fitur
# Jika F-score besar rata-rata antar grup beda jauh → fitur mungkin sangat informatif
# Jika F-score kecil rata-rata antar grup mirip → fitur mungkin tidak informatif
scores = selector.scores_

# Membuat DataFrame untuk menampilkan hasil
num_feature_scores = pd.DataFrame({'Feature': X_anova.columns, 'ANOVA F-Score': scores})
num_feature_scores = num_feature_scores.sort_values(by='ANOVA F-Score', ascending=False)

print(num_feature_scores)

del num_cols, X_anova, y_anova, selector, scores, num_feature_scores

                     Feature  ANOVA F-Score
5  latest_ecommerce_progress    1123.000774
0                    bounces     995.498781
2                  pageviews     656.858064
3                       hits     597.679893
1               time_on_site     397.910993
4        session_quality_dim      31.761898
6          avg_time_per_page       0.570615

### 4.4 Target Encoder

Mengubah kolom dengan dtype:object menjadi numerik, khusus untuk yang meiliki tipe lebih besar dari 15

*Encode* feature `source` dan `country` dengan Target Encoding, dikarenakan tipe isiannya terlalu banyak (lebih dari 15)

In [50]:
import pandas as pd
from category_encoders import TargetEncoder

encoder = TargetEncoder(cols=['source', 'country'])
train_df_encoded = encoder.fit_transform(train_df[['source', 'country']], train_df['will_buy_on_return_visit'])

train_df['source_encoded'] = train_df_encoded['source']
train_df['country_encoded'] = train_df_encoded['country']

# Buat dictionary untuk mapping test dataset agar sesuai dengan train dataset
source_dict = train_df.drop_duplicates(subset='source').set_index('source')['source_encoded'].to_dict()
country_dict = train_df.drop_duplicates(subset='country').set_index('country')['country_encoded'].to_dict()

del train_df_encoded

In [51]:
# Drop kolom asli 'country' dan 'source' yang masih object
train_df.drop(columns=['country', 'source'], inplace=True)

In [52]:
# Ganti nama kolom encoded
train_df = train_df.rename(columns={'country_encoded': 'country', 'source_encoded': 'source'})

*Encode* test dataset

In [53]:
test_df['country_encoded'] = test_df['country'].map(country_dict)
test_df['source_encoded'] = test_df['source'].map(source_dict)

In [54]:
del country_dict, source_dict

# Karena ada beberapa 'country' dan 'source' baru, sehingga tidak bisa di encode, maka kita isi saja missing valuenya dengan '0'
test_df['country_encoded'] = test_df['country_encoded'].fillna(0)
test_df['source_encoded'] = test_df['source_encoded'].fillna(0)

In [55]:
# Drop kolom 'country' dan 'source' yang asli
test_df.drop(columns=['country', 'source'], inplace=True)

In [56]:
# Rename kolom ke 'country' dan 'source'
test_df = test_df.rename(columns={'country_encoded': 'country', 'source_encoded': 'source'})

In [57]:
# Cek apakah sudah tidak ada missing value
test_df.isna().sum()

bounces                      0
time_on_site                 0
pageviews                    0
hits                         0
session_quality_dim          0
latest_ecommerce_progress    0
avg_time_per_page            0
channelGrouping              0
deviceCategory               0
operatingSystem              0
browser                      0
country                      0
source                       0
dtype: int64

In [58]:
# Fitur yang diseleksi berdasarkan hasil ChiSquare dan ANOVA
feature_selected = ['source', 'country', 'latest_ecommerce_progress', 'bounces']

In [59]:
# Mengclone train dataframe dengan fitur terpilih ke dataframe baru
X = train_df[feature_selected]
y = train_df['will_buy_on_return_visit']

X_pred = test_df[feature_selected]

## 5. Model Training

In [60]:
from sklearn.model_selection import train_test_split

# Membagi data menjadi training dan testing set
# Agar fair kita split diawal saja, karena tiap train_test_split dijalankan hasilnya bisa berbeda
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [61]:
# RandomForestClassifier Accuracy: 0.91875
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report

# Membuat model Random Forest
model = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42)	

# Melatih model
model.fit(X_train, y_train)

# Memprediksi pada data testing
y_pred = model.predict(X_test)

# Evaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

# Cross-validation untuk evaluasi lebih lanjut
cv_scores = cross_val_score(model, X, y, cv=2)
print(f"Cross-Validation Accuracy: {cv_scores.mean()} ± {cv_scores.std()}")

# Membersihkan variabel
del y_pred, accuracy, report, cv_scores

Accuracy: 0.91875
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       407
           1       0.91      0.93      0.92       393

    accuracy                           0.92       800
   macro avg       0.92      0.92      0.92       800
weighted avg       0.92      0.92      0.92       800

Cross-Validation Accuracy: 0.8947499999999999 ± 0.000749999999999973

In [62]:
# DecisionTreeClassifier Accuracy: 0.915
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report

# Membuat model Decision Tree
model = DecisionTreeClassifier(max_depth=6, random_state=42)

# Melatih model
model.fit(X_train, y_train)

# Memprediksi pada data testing
y_pred = model.predict(X_test)

# Evaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

# Cross-validation untuk evaluasi lebih lanjut
cv_scores = cross_val_score(model, X, y, cv=2)
print(f"Cross-Validation Accuracy: {cv_scores.mean()} ± {cv_scores.std()}")

# Membersihkan variabel
del y_pred, accuracy, report, cv_scores

Accuracy: 0.915
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.90      0.92       407
           1       0.90      0.93      0.91       393

    accuracy                           0.92       800
   macro avg       0.92      0.92      0.91       800
weighted avg       0.92      0.92      0.92       800

Cross-Validation Accuracy: 0.887 ± 0.0

In [63]:
# XGBClassifier Accuracy: 0.91625
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report

# Membuat model XGBoost
model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=6, 
                      use_label_encoder=False, eval_metric='mlogloss', verbosity=0, random_state=42)

# Melatih model
model.fit(X_train, y_train)

# Memprediksi pada data testing
y_pred = model.predict(X_test)

# Evaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

# Cross-validation untuk evaluasi lebih lanjut
cv_scores = cross_val_score(model, X, y, cv=2)
print(f"Cross-Validation Accuracy: {cv_scores.mean()} ± {cv_scores.std()}")

# Membersihkan variabel
del y_pred, accuracy, report, cv_scores

Accuracy: 0.91625
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.90      0.92       407
           1       0.90      0.93      0.92       393

    accuracy                           0.92       800
   macro avg       0.92      0.92      0.92       800
weighted avg       0.92      0.92      0.92       800

Cross-Validation Accuracy: 0.89525 ± 0.00024999999999997247

In [64]:
# GradientBoostingClassifier Accuracy: 0.91125
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report

# Membuat model Gradient Boosting
model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)

# Melatih model
model.fit(X_train, y_train)

# Memprediksi pada data testing
y_pred = model.predict(X_test)

# Evaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

# Cross-validation untuk evaluasi lebih lanjut
cv_scores = cross_val_score(model, X, y, cv=2)
print(f"Cross-Validation Accuracy: {cv_scores.mean()} ± {cv_scores.std()}")

# Membersihkan variabel
del y_pred, accuracy, report, cv_scores

Accuracy: 0.91125
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       407
           1       0.90      0.93      0.91       393

    accuracy                           0.91       800
   macro avg       0.91      0.91      0.91       800
weighted avg       0.91      0.91      0.91       800

Cross-Validation Accuracy: 0.8907499999999999 ± 0.0032500000000000306

In [65]:
# CatBoostClassifier, Public score 0.9042857, Accuracy: 0.91625
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report

# Membuat model CatBoost
model = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=6, verbose=0)

# Melatih model
model.fit(X_train, y_train)

# Memprediksi pada data testing
y_pred = model.predict(X_test)

# Evaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

# Cross-validation untuk evaluasi lebih lanjut
cv_scores = cross_val_score(model, X, y, cv=2)
print(f"Cross-Validation Accuracy: {cv_scores.mean()} ± {cv_scores.std()}")

del y_pred, accuracy, report, cv_scores

Accuracy: 0.91625
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       407
           1       0.91      0.92      0.92       393

    accuracy                           0.92       800
   macro avg       0.92      0.92      0.92       800
weighted avg       0.92      0.92      0.92       800

Cross-Validation Accuracy: 0.8959999999999999 ± 0.0005000000000000004

In [66]:
# Karena algortima CatBoost public scorenya baik saat dipush, maka kita menggunakan model tersebut

nomor = 0
submission = pd.read_csv('../sample_submission.csv')
submission['will_buy_on_return_visit'] = model.predict(X_pred)
submission.to_csv(f'submission-{nomor}.csv', index=False, header=True)

del nomor